- hosts: all
  become: true
#   become_user: root
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      delay: 30
      
    - name: Apt for sure
      apt: name=foobar state=installed
      register: apt_status
      until: apt_status is success
      delay: 15
      retries: 10
      
    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes
      retries: 3
      delay: 3

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
